//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeOutputInitParameters) DeepCopyInto(out *DescribeOutputInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeOutputInitParameters.
func (in *DescribeOutputInitParameters) DeepCopy() *DescribeOutputInitParameters {
	if in == nil {
		return nil
	}
	out := new(DescribeOutputInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeOutputObservation) DeepCopyInto(out *DescribeOutputObservation) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.IntegrationName != nil {
		in, out := &in.IntegrationName, &out.IntegrationName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OauthAccessTokenExpiryTime != nil {
		in, out := &in.OauthAccessTokenExpiryTime, &out.OauthAccessTokenExpiryTime
		*out = new(string)
		**out = **in
	}
	if in.OauthRefreshTokenExpiryTime != nil {
		in, out := &in.OauthRefreshTokenExpiryTime, &out.OauthRefreshTokenExpiryTime
		*out = new(string)
		**out = **in
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.SchemaName != nil {
		in, out := &in.SchemaName, &out.SchemaName
		*out = new(string)
		**out = **in
	}
	if in.SecretType != nil {
		in, out := &in.SecretType, &out.SecretType
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeOutputObservation.
func (in *DescribeOutputObservation) DeepCopy() *DescribeOutputObservation {
	if in == nil {
		return nil
	}
	out := new(DescribeOutputObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeOutputParameters) DeepCopyInto(out *DescribeOutputParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeOutputParameters.
func (in *DescribeOutputParameters) DeepCopy() *DescribeOutputParameters {
	if in == nil {
		return nil
	}
	out := new(DescribeOutputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputInitParameters) DeepCopyInto(out *ShowOutputInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputInitParameters.
func (in *ShowOutputInitParameters) DeepCopy() *ShowOutputInitParameters {
	if in == nil {
		return nil
	}
	out := new(ShowOutputInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputObservation) DeepCopyInto(out *ShowOutputObservation) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.OwnerRoleType != nil {
		in, out := &in.OwnerRoleType, &out.OwnerRoleType
		*out = new(string)
		**out = **in
	}
	if in.SchemaName != nil {
		in, out := &in.SchemaName, &out.SchemaName
		*out = new(string)
		**out = **in
	}
	if in.SecretType != nil {
		in, out := &in.SecretType, &out.SecretType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputObservation.
func (in *ShowOutputObservation) DeepCopy() *ShowOutputObservation {
	if in == nil {
		return nil
	}
	out := new(ShowOutputObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputParameters) DeepCopyInto(out *ShowOutputParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputParameters.
func (in *ShowOutputParameters) DeepCopy() *ShowOutputParameters {
	if in == nil {
		return nil
	}
	out := new(ShowOutputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WithAuthorizationCodeGrant) DeepCopyInto(out *WithAuthorizationCodeGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WithAuthorizationCodeGrant.
func (in *WithAuthorizationCodeGrant) DeepCopy() *WithAuthorizationCodeGrant {
	if in == nil {
		return nil
	}
	out := new(WithAuthorizationCodeGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WithAuthorizationCodeGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WithAuthorizationCodeGrantInitParameters) DeepCopyInto(out *WithAuthorizationCodeGrantInitParameters) {
	*out = *in
	if in.APIAuthentication != nil {
		in, out := &in.APIAuthentication, &out.APIAuthentication
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OauthRefreshTokenExpiryTime != nil {
		in, out := &in.OauthRefreshTokenExpiryTime, &out.OauthRefreshTokenExpiryTime
		*out = new(string)
		**out = **in
	}
	out.OauthRefreshTokenSecretRef = in.OauthRefreshTokenSecretRef
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WithAuthorizationCodeGrantInitParameters.
func (in *WithAuthorizationCodeGrantInitParameters) DeepCopy() *WithAuthorizationCodeGrantInitParameters {
	if in == nil {
		return nil
	}
	out := new(WithAuthorizationCodeGrantInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WithAuthorizationCodeGrantList) DeepCopyInto(out *WithAuthorizationCodeGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WithAuthorizationCodeGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WithAuthorizationCodeGrantList.
func (in *WithAuthorizationCodeGrantList) DeepCopy() *WithAuthorizationCodeGrantList {
	if in == nil {
		return nil
	}
	out := new(WithAuthorizationCodeGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WithAuthorizationCodeGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WithAuthorizationCodeGrantObservation) DeepCopyInto(out *WithAuthorizationCodeGrantObservation) {
	*out = *in
	if in.APIAuthentication != nil {
		in, out := &in.APIAuthentication, &out.APIAuthentication
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.DescribeOutput != nil {
		in, out := &in.DescribeOutput, &out.DescribeOutput
		*out = make([]DescribeOutputObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FullyQualifiedName != nil {
		in, out := &in.FullyQualifiedName, &out.FullyQualifiedName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OauthRefreshTokenExpiryTime != nil {
		in, out := &in.OauthRefreshTokenExpiryTime, &out.OauthRefreshTokenExpiryTime
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SecretType != nil {
		in, out := &in.SecretType, &out.SecretType
		*out = new(string)
		**out = **in
	}
	if in.ShowOutput != nil {
		in, out := &in.ShowOutput, &out.ShowOutput
		*out = make([]ShowOutputObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WithAuthorizationCodeGrantObservation.
func (in *WithAuthorizationCodeGrantObservation) DeepCopy() *WithAuthorizationCodeGrantObservation {
	if in == nil {
		return nil
	}
	out := new(WithAuthorizationCodeGrantObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WithAuthorizationCodeGrantParameters) DeepCopyInto(out *WithAuthorizationCodeGrantParameters) {
	*out = *in
	if in.APIAuthentication != nil {
		in, out := &in.APIAuthentication, &out.APIAuthentication
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OauthRefreshTokenExpiryTime != nil {
		in, out := &in.OauthRefreshTokenExpiryTime, &out.OauthRefreshTokenExpiryTime
		*out = new(string)
		**out = **in
	}
	out.OauthRefreshTokenSecretRef = in.OauthRefreshTokenSecretRef
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WithAuthorizationCodeGrantParameters.
func (in *WithAuthorizationCodeGrantParameters) DeepCopy() *WithAuthorizationCodeGrantParameters {
	if in == nil {
		return nil
	}
	out := new(WithAuthorizationCodeGrantParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WithAuthorizationCodeGrantSpec) DeepCopyInto(out *WithAuthorizationCodeGrantSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WithAuthorizationCodeGrantSpec.
func (in *WithAuthorizationCodeGrantSpec) DeepCopy() *WithAuthorizationCodeGrantSpec {
	if in == nil {
		return nil
	}
	out := new(WithAuthorizationCodeGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WithAuthorizationCodeGrantStatus) DeepCopyInto(out *WithAuthorizationCodeGrantStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WithAuthorizationCodeGrantStatus.
func (in *WithAuthorizationCodeGrantStatus) DeepCopy() *WithAuthorizationCodeGrantStatus {
	if in == nil {
		return nil
	}
	out := new(WithAuthorizationCodeGrantStatus)
	in.DeepCopyInto(out)
	return out
}
