// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DescribeOutputInitParameters struct {
}

type DescribeOutputObservation struct {

	// (String) Specifies a comment for the secret.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (String)
	IntegrationName *string `json:"integrationName,omitempty" tf:"integration_name,omitempty"`

	// (String) String that specifies the identifier (i.e. name) for the secret, must be unique in your schema. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	OauthAccessTokenExpiryTime *string `json:"oauthAccessTokenExpiryTime,omitempty" tf:"oauth_access_token_expiry_time,omitempty"`

	// MM-DD, YYYY-MM-DD HH:MI, YYYY-MM-DD HH:MI:SS, YYYY-MM-DD HH:MI
	OauthRefreshTokenExpiryTime *string `json:"oauthRefreshTokenExpiryTime,omitempty" tf:"oauth_refresh_token_expiry_time,omitempty"`

	// (Set of String)
	// +listType=set
	OauthScopes []*string `json:"oauthScopes,omitempty" tf:"oauth_scopes,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// (String) Specifies a type for the secret. This field is used for checking external changes and recreating the resources if needed.
	SecretType *string `json:"secretType,omitempty" tf:"secret_type,omitempty"`

	// (String)
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type DescribeOutputParameters struct {
}

type ShowOutputInitParameters struct {
}

type ShowOutputObservation struct {

	// (String) Specifies a comment for the secret.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (String) String that specifies the identifier (i.e. name) for the secret, must be unique in your schema. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String)
	// +listType=set
	OauthScopes []*string `json:"oauthScopes,omitempty" tf:"oauth_scopes,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// (String) Specifies a type for the secret. This field is used for checking external changes and recreating the resources if needed.
	SecretType *string `json:"secretType,omitempty" tf:"secret_type,omitempty"`
}

type ShowOutputParameters struct {
}

type WithAuthorizationCodeGrantInitParameters struct {

	// (String) Specifies the name value of the Snowflake security integration that connects Snowflake to an external service. For more information about this resource, see docs.
	// Specifies the name value of the Snowflake security integration that connects Snowflake to an external service. For more information about this resource, see [docs](./api_authentication_integration_with_authorization_code_grant).
	APIAuthentication *string `json:"apiAuthentication,omitempty" tf:"api_authentication,omitempty"`

	// (String) Specifies a comment for the secret.
	// Specifies a comment for the secret.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the secret Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the secret Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) String that specifies the identifier (i.e. name) for the secret, must be unique in your schema. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// String that specifies the identifier (i.e. name) for the secret, must be unique in your schema. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// MM-DD, YYYY-MM-DD HH:MI, YYYY-MM-DD HH:MI:SS, YYYY-MM-DD HH:MI
	// Specifies the timestamp as a string when the OAuth refresh token expires. Accepted string formats: YYYY-MM-DD, YYYY-MM-DD HH:MI, YYYY-MM-DD HH:MI:SS, YYYY-MM-DD HH:MI <timezone>
	OauthRefreshTokenExpiryTime *string `json:"oauthRefreshTokenExpiryTime,omitempty" tf:"oauth_refresh_token_expiry_time,omitempty"`

	// Specifies the token as a string that is used to obtain a new access token from the OAuth authorization server when the access token expires. External changes for this field won't be detected.
	OauthRefreshTokenSecretRef v1.SecretKeySelector `json:"oauthRefreshTokenSecretRef" tf:"-"`

	// (String) The schema in which to create the secret. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the secret. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type WithAuthorizationCodeGrantObservation struct {

	// (String) Specifies the name value of the Snowflake security integration that connects Snowflake to an external service. For more information about this resource, see docs.
	// Specifies the name value of the Snowflake security integration that connects Snowflake to an external service. For more information about this resource, see [docs](./api_authentication_integration_with_authorization_code_grant).
	APIAuthentication *string `json:"apiAuthentication,omitempty" tf:"api_authentication,omitempty"`

	// (String) Specifies a comment for the secret.
	// Specifies a comment for the secret.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the secret Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the secret Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE SECRET for the given secret. (see below for nested schema)
	// Outputs the result of `DESCRIBE SECRET` for the given secret.
	DescribeOutput []DescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String that specifies the identifier (i.e. name) for the secret, must be unique in your schema. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// String that specifies the identifier (i.e. name) for the secret, must be unique in your schema. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// MM-DD, YYYY-MM-DD HH:MI, YYYY-MM-DD HH:MI:SS, YYYY-MM-DD HH:MI
	// Specifies the timestamp as a string when the OAuth refresh token expires. Accepted string formats: YYYY-MM-DD, YYYY-MM-DD HH:MI, YYYY-MM-DD HH:MI:SS, YYYY-MM-DD HH:MI <timezone>
	OauthRefreshTokenExpiryTime *string `json:"oauthRefreshTokenExpiryTime,omitempty" tf:"oauth_refresh_token_expiry_time,omitempty"`

	// (String) The schema in which to create the secret. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the secret. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) Specifies a type for the secret. This field is used for checking external changes and recreating the resources if needed.
	// Specifies a type for the secret. This field is used for checking external changes and recreating the resources if needed.
	SecretType *string `json:"secretType,omitempty" tf:"secret_type,omitempty"`

	// (List of Object) Outputs the result of SHOW SECRETS for the given secret. (see below for nested schema)
	// Outputs the result of `SHOW SECRETS` for the given secret.
	ShowOutput []ShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type WithAuthorizationCodeGrantParameters struct {

	// (String) Specifies the name value of the Snowflake security integration that connects Snowflake to an external service. For more information about this resource, see docs.
	// Specifies the name value of the Snowflake security integration that connects Snowflake to an external service. For more information about this resource, see [docs](./api_authentication_integration_with_authorization_code_grant).
	// +kubebuilder:validation:Optional
	APIAuthentication *string `json:"apiAuthentication,omitempty" tf:"api_authentication,omitempty"`

	// (String) Specifies a comment for the secret.
	// Specifies a comment for the secret.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the secret Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the secret Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) String that specifies the identifier (i.e. name) for the secret, must be unique in your schema. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// String that specifies the identifier (i.e. name) for the secret, must be unique in your schema. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// MM-DD, YYYY-MM-DD HH:MI, YYYY-MM-DD HH:MI:SS, YYYY-MM-DD HH:MI
	// Specifies the timestamp as a string when the OAuth refresh token expires. Accepted string formats: YYYY-MM-DD, YYYY-MM-DD HH:MI, YYYY-MM-DD HH:MI:SS, YYYY-MM-DD HH:MI <timezone>
	// +kubebuilder:validation:Optional
	OauthRefreshTokenExpiryTime *string `json:"oauthRefreshTokenExpiryTime,omitempty" tf:"oauth_refresh_token_expiry_time,omitempty"`

	// Specifies the token as a string that is used to obtain a new access token from the OAuth authorization server when the access token expires. External changes for this field won't be detected.
	// +kubebuilder:validation:Optional
	OauthRefreshTokenSecretRef v1.SecretKeySelector `json:"oauthRefreshTokenSecretRef" tf:"-"`

	// (String) The schema in which to create the secret. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the secret. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

// WithAuthorizationCodeGrantSpec defines the desired state of WithAuthorizationCodeGrant
type WithAuthorizationCodeGrantSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WithAuthorizationCodeGrantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WithAuthorizationCodeGrantInitParameters `json:"initProvider,omitempty"`
}

// WithAuthorizationCodeGrantStatus defines the observed state of WithAuthorizationCodeGrant.
type WithAuthorizationCodeGrantStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WithAuthorizationCodeGrantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WithAuthorizationCodeGrant is the Schema for the WithAuthorizationCodeGrants API. Resource used to manage secret objects with OAuth Authorization Code Grant. For more information, check secret documentation https://docs.snowflake.com/en/sql-reference/sql/create-secret.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type WithAuthorizationCodeGrant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiAuthentication) || (has(self.initProvider) && has(self.initProvider.apiAuthentication))",message="spec.forProvider.apiAuthentication is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oauthRefreshTokenSecretRef)",message="spec.forProvider.oauthRefreshTokenSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oauthRefreshTokenExpiryTime) || (has(self.initProvider) && has(self.initProvider.oauthRefreshTokenExpiryTime))",message="spec.forProvider.oauthRefreshTokenExpiryTime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schema) || (has(self.initProvider) && has(self.initProvider.schema))",message="spec.forProvider.schema is a required parameter"
	Spec   WithAuthorizationCodeGrantSpec   `json:"spec"`
	Status WithAuthorizationCodeGrantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WithAuthorizationCodeGrantList contains a list of WithAuthorizationCodeGrants
type WithAuthorizationCodeGrantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WithAuthorizationCodeGrant `json:"items"`
}

// Repository type metadata.
var (
	WithAuthorizationCodeGrant_Kind             = "WithAuthorizationCodeGrant"
	WithAuthorizationCodeGrant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WithAuthorizationCodeGrant_Kind}.String()
	WithAuthorizationCodeGrant_KindAPIVersion   = WithAuthorizationCodeGrant_Kind + "." + CRDGroupVersion.String()
	WithAuthorizationCodeGrant_GroupVersionKind = CRDGroupVersion.WithKind(WithAuthorizationCodeGrant_Kind)
)

func init() {
	SchemeBuilder.Register(&WithAuthorizationCodeGrant{}, &WithAuthorizationCodeGrantList{})
}
