apiVersion: snowflakeexecute.crossplane.io/v1alpha1
kind: Execute
metadata:
  annotations:
    meta.upbound.io/example-id: snowflakeexecute/v1alpha1/execute
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    execute: CREATE DATABASE ABC
    revert: DROP DATABASE ABC
