// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AllInitParameters struct {

	// (String)
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// (String) The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	// The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type AllObservation struct {

	// (String)
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// (String) The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	// The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type AllParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// (String) The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	// The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	// +kubebuilder:validation:Optional
	ObjectTypePlural *string `json:"objectTypePlural" tf:"object_type_plural,omitempty"`
}

type FutureInitParameters struct {

	// (String)
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// (String) The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	// The plural object type of the schema object on which privileges will be granted. Valid values are: ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | ICEBERG TABLES | JOIN POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | SECRETS | SEMANTIC VIEWS | SERVICES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TASKS | VIEWS.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type FutureObservation struct {

	// (String)
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// (String) The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	// The plural object type of the schema object on which privileges will be granted. Valid values are: ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | ICEBERG TABLES | JOIN POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | SECRETS | SEMANTIC VIEWS | SERVICES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TASKS | VIEWS.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type FutureParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// (String) The plural object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICIES | ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | IMAGE REPOSITORIES | ICEBERG TABLES | JOIN POLICIES | MASKING POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PACKAGES POLICIES | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | PROJECTION POLICIES | ROW ACCESS POLICIES | SECRETS | SEMANTIC VIEWS | SERVICES | SESSION POLICIES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TAGS | TASKS | VIEWS.
	// The plural object type of the schema object on which privileges will be granted. Valid values are: ALERTS | AUTHENTICATION POLICIES | CORTEX SEARCH SERVICES | DATA METRIC FUNCTIONS | DATASETS | DBT PROJECTS | DYNAMIC TABLES | EVENT TABLES | EXTERNAL TABLES | FILE FORMATS | FUNCTIONS | GIT REPOSITORIES | HYBRID TABLES | ICEBERG TABLES | JOIN POLICIES | MATERIALIZED VIEWS | MODELS | MODEL MONITORS | NETWORK RULES | NOTEBOOKS | PASSWORD POLICIES | PIPES | PRIVACY POLICIES | PROCEDURES | SECRETS | SEMANTIC VIEWS | SERVICES | SEQUENCES | SNAPSHOTS | SNAPSHOT POLICIES | SNAPSHOT SETS | STAGES | STREAMS | STREAMLITS | TABLES | TASKS | VIEWS.
	// +kubebuilder:validation:Optional
	ObjectTypePlural *string `json:"objectTypePlural" tf:"object_type_plural,omitempty"`
}

type OnAccountObjectInitParameters struct {

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// (String) The object type of the account object on which privileges will be granted. Valid values are: USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME
	// The object type of the account object on which privileges will be granted. Valid values are: `USER` | `RESOURCE MONITOR` | `WAREHOUSE` | `COMPUTE POOL` | `DATABASE` | `INTEGRATION` | `FAILOVER GROUP` | `REPLICATION GROUP` | `EXTERNAL VOLUME`
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnAccountObjectObservation struct {

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// (String) The object type of the account object on which privileges will be granted. Valid values are: USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME
	// The object type of the account object on which privileges will be granted. Valid values are: `USER` | `RESOURCE MONITOR` | `WAREHOUSE` | `COMPUTE POOL` | `DATABASE` | `INTEGRATION` | `FAILOVER GROUP` | `REPLICATION GROUP` | `EXTERNAL VOLUME`
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnAccountObjectParameters struct {

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	// +kubebuilder:validation:Optional
	ObjectName *string `json:"objectName" tf:"object_name,omitempty"`

	// (String) The object type of the account object on which privileges will be granted. Valid values are: USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME
	// The object type of the account object on which privileges will be granted. Valid values are: `USER` | `RESOURCE MONITOR` | `WAREHOUSE` | `COMPUTE POOL` | `DATABASE` | `INTEGRATION` | `FAILOVER GROUP` | `REPLICATION GROUP` | `EXTERNAL VOLUME`
	// +kubebuilder:validation:Optional
	ObjectType *string `json:"objectType" tf:"object_type,omitempty"`
}

type OnSchemaInitParameters struct {

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	AllSchemasInDatabase *string `json:"allSchemasInDatabase,omitempty" tf:"all_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	FutureSchemasInDatabase *string `json:"futureSchemasInDatabase,omitempty" tf:"future_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the schema.
	// The fully qualified name of the schema.
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type OnSchemaObjectInitParameters struct {

	// (Block List, Max: 1) Configures the privilege to be granted on all objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on all objects in either a database or schema.
	All []AllInitParameters `json:"all,omitempty" tf:"all,omitempty"`

	// (Block List, Max: 1) Configures the privilege to be granted on future objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on future objects in either a database or schema.
	Future []FutureInitParameters `json:"future,omitempty" tf:"future,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// (String) The object type of the account object on which privileges will be granted. Valid values are: USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME
	// The object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICY | ALERT | AUTHENTICATION POLICY | CORTEX SEARCH SERVICE | DATA METRIC FUNCTION | DATASET | DBT PROJECT | DYNAMIC TABLE | EVENT TABLE | EXTERNAL TABLE | FILE FORMAT | FUNCTION | GIT REPOSITORY | HYBRID TABLE | IMAGE REPOSITORY | ICEBERG TABLE | JOIN POLICY | MASKING POLICY | MATERIALIZED VIEW | MODEL | MODEL MONITOR | NETWORK RULE | NOTEBOOK | PACKAGES POLICY | PASSWORD POLICY | PIPE | PRIVACY POLICY | PROCEDURE | PROJECTION POLICY | ROW ACCESS POLICY | SECRET | SEMANTIC VIEW | SERVICE | SESSION POLICY | SEQUENCE | SNAPSHOT | SNAPSHOT POLICY | SNAPSHOT SET | STAGE | STREAM | STREAMLIT | TABLE | TAG | TASK | VIEW
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnSchemaObjectObservation struct {

	// (Block List, Max: 1) Configures the privilege to be granted on all objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on all objects in either a database or schema.
	All []AllObservation `json:"all,omitempty" tf:"all,omitempty"`

	// (Block List, Max: 1) Configures the privilege to be granted on future objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on future objects in either a database or schema.
	Future []FutureObservation `json:"future,omitempty" tf:"future,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// (String) The object type of the account object on which privileges will be granted. Valid values are: USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME
	// The object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICY | ALERT | AUTHENTICATION POLICY | CORTEX SEARCH SERVICE | DATA METRIC FUNCTION | DATASET | DBT PROJECT | DYNAMIC TABLE | EVENT TABLE | EXTERNAL TABLE | FILE FORMAT | FUNCTION | GIT REPOSITORY | HYBRID TABLE | IMAGE REPOSITORY | ICEBERG TABLE | JOIN POLICY | MASKING POLICY | MATERIALIZED VIEW | MODEL | MODEL MONITOR | NETWORK RULE | NOTEBOOK | PACKAGES POLICY | PASSWORD POLICY | PIPE | PRIVACY POLICY | PROCEDURE | PROJECTION POLICY | ROW ACCESS POLICY | SECRET | SEMANTIC VIEW | SERVICE | SESSION POLICY | SEQUENCE | SNAPSHOT | SNAPSHOT POLICY | SNAPSHOT SET | STAGE | STREAM | STREAMLIT | TABLE | TAG | TASK | VIEW
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnSchemaObjectParameters struct {

	// (Block List, Max: 1) Configures the privilege to be granted on all objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on all objects in either a database or schema.
	// +kubebuilder:validation:Optional
	All []AllParameters `json:"all,omitempty" tf:"all,omitempty"`

	// (Block List, Max: 1) Configures the privilege to be granted on future objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on future objects in either a database or schema.
	// +kubebuilder:validation:Optional
	Future []FutureParameters `json:"future,omitempty" tf:"future,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	// +kubebuilder:validation:Optional
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// (String) The object type of the account object on which privileges will be granted. Valid values are: USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME
	// The object type of the schema object on which privileges will be granted. Valid values are: AGGREGATION POLICY | ALERT | AUTHENTICATION POLICY | CORTEX SEARCH SERVICE | DATA METRIC FUNCTION | DATASET | DBT PROJECT | DYNAMIC TABLE | EVENT TABLE | EXTERNAL TABLE | FILE FORMAT | FUNCTION | GIT REPOSITORY | HYBRID TABLE | IMAGE REPOSITORY | ICEBERG TABLE | JOIN POLICY | MASKING POLICY | MATERIALIZED VIEW | MODEL | MODEL MONITOR | NETWORK RULE | NOTEBOOK | PACKAGES POLICY | PASSWORD POLICY | PIPE | PRIVACY POLICY | PROCEDURE | PROJECTION POLICY | ROW ACCESS POLICY | SECRET | SEMANTIC VIEW | SERVICE | SESSION POLICY | SEQUENCE | SNAPSHOT | SNAPSHOT POLICY | SNAPSHOT SET | STAGE | STREAM | STREAMLIT | TABLE | TAG | TASK | VIEW
	// +kubebuilder:validation:Optional
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnSchemaObservation struct {

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	AllSchemasInDatabase *string `json:"allSchemasInDatabase,omitempty" tf:"all_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	FutureSchemasInDatabase *string `json:"futureSchemasInDatabase,omitempty" tf:"future_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the schema.
	// The fully qualified name of the schema.
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type OnSchemaParameters struct {

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	// +kubebuilder:validation:Optional
	AllSchemasInDatabase *string `json:"allSchemasInDatabase,omitempty" tf:"all_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	// +kubebuilder:validation:Optional
	FutureSchemasInDatabase *string `json:"futureSchemasInDatabase,omitempty" tf:"future_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the schema.
	// The fully qualified name of the schema.
	// +kubebuilder:validation:Optional
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type PrivilegesToAccountRoleInitParameters struct {

	// (String) The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see docs.
	// The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see [docs](./account_role).
	AccountRoleName *string `json:"accountRoleName,omitempty" tf:"account_role_name,omitempty"`

	// (Boolean) (Default: false) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	// (Default: `false`) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	AllPrivileges *bool `json:"allPrivileges,omitempty" tf:"all_privileges,omitempty"`

	// grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	// (Default: `false`) If true, the resource will always produce a “plan” and on “apply” it will re-grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	AlwaysApply *bool `json:"alwaysApply,omitempty" tf:"always_apply,omitempty"`

	// (String) (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	// (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	AlwaysApplyTrigger *string `json:"alwaysApplyTrigger,omitempty" tf:"always_apply_trigger,omitempty"`

	// (Boolean) (Default: false) If true, the privileges will be granted on the account.
	// (Default: `false`) If true, the privileges will be granted on the account.
	OnAccount *bool `json:"onAccount,omitempty" tf:"on_account,omitempty"`

	// (Block List, Max: 1) Specifies the account object on which privileges will be granted (see below for nested schema)
	// Specifies the account object on which privileges will be granted
	OnAccountObject []OnAccountObjectInitParameters `json:"onAccountObject,omitempty" tf:"on_account_object,omitempty"`

	// (Block List, Max: 1) Specifies the schema on which privileges will be granted. (see below for nested schema)
	// Specifies the schema on which privileges will be granted.
	OnSchema []OnSchemaInitParameters `json:"onSchema,omitempty" tf:"on_schema,omitempty"`

	// (Block List, Max: 1) Specifies the schema object on which privileges will be granted. (see below for nested schema)
	// Specifies the schema object on which privileges will be granted.
	OnSchemaObject []OnSchemaObjectInitParameters `json:"onSchemaObject,omitempty" tf:"on_schema_object,omitempty"`

	// sensitive; use only upper-case privileges.
	// The privileges to grant on the account role. This field is case-sensitive; use only upper-case privileges.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (Boolean) (Default: false) Specifies whether the grantee can grant the privileges to other users.
	// (Default: `false`) Specifies whether the grantee can grant the privileges to other users.
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

type PrivilegesToAccountRoleObservation struct {

	// (String) The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see docs.
	// The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see [docs](./account_role).
	AccountRoleName *string `json:"accountRoleName,omitempty" tf:"account_role_name,omitempty"`

	// (Boolean) (Default: false) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	// (Default: `false`) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	AllPrivileges *bool `json:"allPrivileges,omitempty" tf:"all_privileges,omitempty"`

	// grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	// (Default: `false`) If true, the resource will always produce a “plan” and on “apply” it will re-grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	AlwaysApply *bool `json:"alwaysApply,omitempty" tf:"always_apply,omitempty"`

	// (String) (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	// (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	AlwaysApplyTrigger *string `json:"alwaysApplyTrigger,omitempty" tf:"always_apply_trigger,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) (Default: false) If true, the privileges will be granted on the account.
	// (Default: `false`) If true, the privileges will be granted on the account.
	OnAccount *bool `json:"onAccount,omitempty" tf:"on_account,omitempty"`

	// (Block List, Max: 1) Specifies the account object on which privileges will be granted (see below for nested schema)
	// Specifies the account object on which privileges will be granted
	OnAccountObject []OnAccountObjectObservation `json:"onAccountObject,omitempty" tf:"on_account_object,omitempty"`

	// (Block List, Max: 1) Specifies the schema on which privileges will be granted. (see below for nested schema)
	// Specifies the schema on which privileges will be granted.
	OnSchema []OnSchemaObservation `json:"onSchema,omitempty" tf:"on_schema,omitempty"`

	// (Block List, Max: 1) Specifies the schema object on which privileges will be granted. (see below for nested schema)
	// Specifies the schema object on which privileges will be granted.
	OnSchemaObject []OnSchemaObjectObservation `json:"onSchemaObject,omitempty" tf:"on_schema_object,omitempty"`

	// sensitive; use only upper-case privileges.
	// The privileges to grant on the account role. This field is case-sensitive; use only upper-case privileges.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (Boolean) (Default: false) Specifies whether the grantee can grant the privileges to other users.
	// (Default: `false`) Specifies whether the grantee can grant the privileges to other users.
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

type PrivilegesToAccountRoleParameters struct {

	// (String) The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see docs.
	// The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see [docs](./account_role).
	// +kubebuilder:validation:Optional
	AccountRoleName *string `json:"accountRoleName,omitempty" tf:"account_role_name,omitempty"`

	// (Boolean) (Default: false) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	// (Default: `false`) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	// +kubebuilder:validation:Optional
	AllPrivileges *bool `json:"allPrivileges,omitempty" tf:"all_privileges,omitempty"`

	// grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	// (Default: `false`) If true, the resource will always produce a “plan” and on “apply” it will re-grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	// +kubebuilder:validation:Optional
	AlwaysApply *bool `json:"alwaysApply,omitempty" tf:"always_apply,omitempty"`

	// (String) (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	// (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	// +kubebuilder:validation:Optional
	AlwaysApplyTrigger *string `json:"alwaysApplyTrigger,omitempty" tf:"always_apply_trigger,omitempty"`

	// (Boolean) (Default: false) If true, the privileges will be granted on the account.
	// (Default: `false`) If true, the privileges will be granted on the account.
	// +kubebuilder:validation:Optional
	OnAccount *bool `json:"onAccount,omitempty" tf:"on_account,omitempty"`

	// (Block List, Max: 1) Specifies the account object on which privileges will be granted (see below for nested schema)
	// Specifies the account object on which privileges will be granted
	// +kubebuilder:validation:Optional
	OnAccountObject []OnAccountObjectParameters `json:"onAccountObject,omitempty" tf:"on_account_object,omitempty"`

	// (Block List, Max: 1) Specifies the schema on which privileges will be granted. (see below for nested schema)
	// Specifies the schema on which privileges will be granted.
	// +kubebuilder:validation:Optional
	OnSchema []OnSchemaParameters `json:"onSchema,omitempty" tf:"on_schema,omitempty"`

	// (Block List, Max: 1) Specifies the schema object on which privileges will be granted. (see below for nested schema)
	// Specifies the schema object on which privileges will be granted.
	// +kubebuilder:validation:Optional
	OnSchemaObject []OnSchemaObjectParameters `json:"onSchemaObject,omitempty" tf:"on_schema_object,omitempty"`

	// sensitive; use only upper-case privileges.
	// The privileges to grant on the account role. This field is case-sensitive; use only upper-case privileges.
	// +kubebuilder:validation:Optional
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (Boolean) (Default: false) Specifies whether the grantee can grant the privileges to other users.
	// (Default: `false`) Specifies whether the grantee can grant the privileges to other users.
	// +kubebuilder:validation:Optional
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

// PrivilegesToAccountRoleSpec defines the desired state of PrivilegesToAccountRole
type PrivilegesToAccountRoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PrivilegesToAccountRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PrivilegesToAccountRoleInitParameters `json:"initProvider,omitempty"`
}

// PrivilegesToAccountRoleStatus defines the observed state of PrivilegesToAccountRole.
type PrivilegesToAccountRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PrivilegesToAccountRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PrivilegesToAccountRole is the Schema for the PrivilegesToAccountRoles API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type PrivilegesToAccountRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountRoleName) || (has(self.initProvider) && has(self.initProvider.accountRoleName))",message="spec.forProvider.accountRoleName is a required parameter"
	Spec   PrivilegesToAccountRoleSpec   `json:"spec"`
	Status PrivilegesToAccountRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrivilegesToAccountRoleList contains a list of PrivilegesToAccountRoles
type PrivilegesToAccountRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrivilegesToAccountRole `json:"items"`
}

// Repository type metadata.
var (
	PrivilegesToAccountRole_Kind             = "PrivilegesToAccountRole"
	PrivilegesToAccountRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PrivilegesToAccountRole_Kind}.String()
	PrivilegesToAccountRole_KindAPIVersion   = PrivilegesToAccountRole_Kind + "." + CRDGroupVersion.String()
	PrivilegesToAccountRole_GroupVersionKind = CRDGroupVersion.WithKind(PrivilegesToAccountRole_Kind)
)

func init() {
	SchemeBuilder.Register(&PrivilegesToAccountRole{}, &PrivilegesToAccountRoleList{})
}
