apiVersion: snowflakedatabase.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: snowflakedatabase/v1alpha1/database
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    name: database_name
