apiVersion: snowflakeresourcemonitor.crossplane.io/v1alpha1
kind: Monitor
metadata:
  annotations:
    meta.upbound.io/example-id: snowflakeresourcemonitor/v1alpha1/monitor
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal
spec:
  forProvider:
    name: resource-monitor-name
