apiVersion: snowflakelegacyserviceuser.crossplane.io/v1alpha1
kind: ServiceUser
metadata:
  annotations:
    meta.upbound.io/example-id: snowflakelegacyserviceuser/v1alpha1/serviceuser
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal
spec:
  forProvider:
    name: Snowflake Legacy Service User - minimal
