//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogInitParameters) DeepCopyInto(out *CatalogInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogInitParameters.
func (in *CatalogInitParameters) DeepCopy() *CatalogInitParameters {
	if in == nil {
		return nil
	}
	out := new(CatalogInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogObservation) DeepCopyInto(out *CatalogObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogObservation.
func (in *CatalogObservation) DeepCopy() *CatalogObservation {
	if in == nil {
		return nil
	}
	out := new(CatalogObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogParameters) DeepCopyInto(out *CatalogParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogParameters.
func (in *CatalogParameters) DeepCopy() *CatalogParameters {
	if in == nil {
		return nil
	}
	out := new(CatalogParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataRetentionTimeInDaysInitParameters) DeepCopyInto(out *DataRetentionTimeInDaysInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataRetentionTimeInDaysInitParameters.
func (in *DataRetentionTimeInDaysInitParameters) DeepCopy() *DataRetentionTimeInDaysInitParameters {
	if in == nil {
		return nil
	}
	out := new(DataRetentionTimeInDaysInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataRetentionTimeInDaysObservation) DeepCopyInto(out *DataRetentionTimeInDaysObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataRetentionTimeInDaysObservation.
func (in *DataRetentionTimeInDaysObservation) DeepCopy() *DataRetentionTimeInDaysObservation {
	if in == nil {
		return nil
	}
	out := new(DataRetentionTimeInDaysObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataRetentionTimeInDaysParameters) DeepCopyInto(out *DataRetentionTimeInDaysParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataRetentionTimeInDaysParameters.
func (in *DataRetentionTimeInDaysParameters) DeepCopy() *DataRetentionTimeInDaysParameters {
	if in == nil {
		return nil
	}
	out := new(DataRetentionTimeInDaysParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDdlCollationInitParameters) DeepCopyInto(out *DefaultDdlCollationInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDdlCollationInitParameters.
func (in *DefaultDdlCollationInitParameters) DeepCopy() *DefaultDdlCollationInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultDdlCollationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDdlCollationObservation) DeepCopyInto(out *DefaultDdlCollationObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDdlCollationObservation.
func (in *DefaultDdlCollationObservation) DeepCopy() *DefaultDdlCollationObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultDdlCollationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultDdlCollationParameters) DeepCopyInto(out *DefaultDdlCollationParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultDdlCollationParameters.
func (in *DefaultDdlCollationParameters) DeepCopy() *DefaultDdlCollationParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultDdlCollationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeOutputInitParameters) DeepCopyInto(out *DescribeOutputInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeOutputInitParameters.
func (in *DescribeOutputInitParameters) DeepCopy() *DescribeOutputInitParameters {
	if in == nil {
		return nil
	}
	out := new(DescribeOutputInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeOutputObservation) DeepCopyInto(out *DescribeOutputObservation) {
	*out = *in
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeOutputObservation.
func (in *DescribeOutputObservation) DeepCopy() *DescribeOutputObservation {
	if in == nil {
		return nil
	}
	out := new(DescribeOutputObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeOutputParameters) DeepCopyInto(out *DescribeOutputParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeOutputParameters.
func (in *DescribeOutputParameters) DeepCopy() *DescribeOutputParameters {
	if in == nil {
		return nil
	}
	out := new(DescribeOutputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableConsoleOutputInitParameters) DeepCopyInto(out *EnableConsoleOutputInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableConsoleOutputInitParameters.
func (in *EnableConsoleOutputInitParameters) DeepCopy() *EnableConsoleOutputInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnableConsoleOutputInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableConsoleOutputObservation) DeepCopyInto(out *EnableConsoleOutputObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableConsoleOutputObservation.
func (in *EnableConsoleOutputObservation) DeepCopy() *EnableConsoleOutputObservation {
	if in == nil {
		return nil
	}
	out := new(EnableConsoleOutputObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableConsoleOutputParameters) DeepCopyInto(out *EnableConsoleOutputParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableConsoleOutputParameters.
func (in *EnableConsoleOutputParameters) DeepCopy() *EnableConsoleOutputParameters {
	if in == nil {
		return nil
	}
	out := new(EnableConsoleOutputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalVolumeInitParameters) DeepCopyInto(out *ExternalVolumeInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalVolumeInitParameters.
func (in *ExternalVolumeInitParameters) DeepCopy() *ExternalVolumeInitParameters {
	if in == nil {
		return nil
	}
	out := new(ExternalVolumeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalVolumeObservation) DeepCopyInto(out *ExternalVolumeObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalVolumeObservation.
func (in *ExternalVolumeObservation) DeepCopy() *ExternalVolumeObservation {
	if in == nil {
		return nil
	}
	out := new(ExternalVolumeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalVolumeParameters) DeepCopyInto(out *ExternalVolumeParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalVolumeParameters.
func (in *ExternalVolumeParameters) DeepCopy() *ExternalVolumeParameters {
	if in == nil {
		return nil
	}
	out := new(ExternalVolumeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogLevelInitParameters) DeepCopyInto(out *LogLevelInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogLevelInitParameters.
func (in *LogLevelInitParameters) DeepCopy() *LogLevelInitParameters {
	if in == nil {
		return nil
	}
	out := new(LogLevelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogLevelObservation) DeepCopyInto(out *LogLevelObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogLevelObservation.
func (in *LogLevelObservation) DeepCopy() *LogLevelObservation {
	if in == nil {
		return nil
	}
	out := new(LogLevelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogLevelParameters) DeepCopyInto(out *LogLevelParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogLevelParameters.
func (in *LogLevelParameters) DeepCopy() *LogLevelParameters {
	if in == nil {
		return nil
	}
	out := new(LogLevelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxDataExtensionTimeInDaysInitParameters) DeepCopyInto(out *MaxDataExtensionTimeInDaysInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxDataExtensionTimeInDaysInitParameters.
func (in *MaxDataExtensionTimeInDaysInitParameters) DeepCopy() *MaxDataExtensionTimeInDaysInitParameters {
	if in == nil {
		return nil
	}
	out := new(MaxDataExtensionTimeInDaysInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxDataExtensionTimeInDaysObservation) DeepCopyInto(out *MaxDataExtensionTimeInDaysObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxDataExtensionTimeInDaysObservation.
func (in *MaxDataExtensionTimeInDaysObservation) DeepCopy() *MaxDataExtensionTimeInDaysObservation {
	if in == nil {
		return nil
	}
	out := new(MaxDataExtensionTimeInDaysObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxDataExtensionTimeInDaysParameters) DeepCopyInto(out *MaxDataExtensionTimeInDaysParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxDataExtensionTimeInDaysParameters.
func (in *MaxDataExtensionTimeInDaysParameters) DeepCopy() *MaxDataExtensionTimeInDaysParameters {
	if in == nil {
		return nil
	}
	out := new(MaxDataExtensionTimeInDaysParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersInitParameters) DeepCopyInto(out *ParametersInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersInitParameters.
func (in *ParametersInitParameters) DeepCopy() *ParametersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ParametersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersObservation) DeepCopyInto(out *ParametersObservation) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = make([]CatalogObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataRetentionTimeInDays != nil {
		in, out := &in.DataRetentionTimeInDays, &out.DataRetentionTimeInDays
		*out = make([]DataRetentionTimeInDaysObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultDdlCollation != nil {
		in, out := &in.DefaultDdlCollation, &out.DefaultDdlCollation
		*out = make([]DefaultDdlCollationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnableConsoleOutput != nil {
		in, out := &in.EnableConsoleOutput, &out.EnableConsoleOutput
		*out = make([]EnableConsoleOutputObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalVolume != nil {
		in, out := &in.ExternalVolume, &out.ExternalVolume
		*out = make([]ExternalVolumeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = make([]LogLevelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxDataExtensionTimeInDays != nil {
		in, out := &in.MaxDataExtensionTimeInDays, &out.MaxDataExtensionTimeInDays
		*out = make([]MaxDataExtensionTimeInDaysObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PipeExecutionPaused != nil {
		in, out := &in.PipeExecutionPaused, &out.PipeExecutionPaused
		*out = make([]PipeExecutionPausedObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QuotedIdentifiersIgnoreCase != nil {
		in, out := &in.QuotedIdentifiersIgnoreCase, &out.QuotedIdentifiersIgnoreCase
		*out = make([]QuotedIdentifiersIgnoreCaseObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReplaceInvalidCharacters != nil {
		in, out := &in.ReplaceInvalidCharacters, &out.ReplaceInvalidCharacters
		*out = make([]ReplaceInvalidCharactersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StorageSerializationPolicy != nil {
		in, out := &in.StorageSerializationPolicy, &out.StorageSerializationPolicy
		*out = make([]StorageSerializationPolicyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SuspendTaskAfterNumFailures != nil {
		in, out := &in.SuspendTaskAfterNumFailures, &out.SuspendTaskAfterNumFailures
		*out = make([]SuspendTaskAfterNumFailuresObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaskAutoRetryAttempts != nil {
		in, out := &in.TaskAutoRetryAttempts, &out.TaskAutoRetryAttempts
		*out = make([]TaskAutoRetryAttemptsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TraceLevel != nil {
		in, out := &in.TraceLevel, &out.TraceLevel
		*out = make([]TraceLevelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserTaskManagedInitialWarehouseSize != nil {
		in, out := &in.UserTaskManagedInitialWarehouseSize, &out.UserTaskManagedInitialWarehouseSize
		*out = make([]UserTaskManagedInitialWarehouseSizeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserTaskMinimumTriggerIntervalInSeconds != nil {
		in, out := &in.UserTaskMinimumTriggerIntervalInSeconds, &out.UserTaskMinimumTriggerIntervalInSeconds
		*out = make([]UserTaskMinimumTriggerIntervalInSecondsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserTaskTimeoutMs != nil {
		in, out := &in.UserTaskTimeoutMs, &out.UserTaskTimeoutMs
		*out = make([]UserTaskTimeoutMsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersObservation.
func (in *ParametersObservation) DeepCopy() *ParametersObservation {
	if in == nil {
		return nil
	}
	out := new(ParametersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersParameters) DeepCopyInto(out *ParametersParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersParameters.
func (in *ParametersParameters) DeepCopy() *ParametersParameters {
	if in == nil {
		return nil
	}
	out := new(ParametersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipeExecutionPausedInitParameters) DeepCopyInto(out *PipeExecutionPausedInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipeExecutionPausedInitParameters.
func (in *PipeExecutionPausedInitParameters) DeepCopy() *PipeExecutionPausedInitParameters {
	if in == nil {
		return nil
	}
	out := new(PipeExecutionPausedInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipeExecutionPausedObservation) DeepCopyInto(out *PipeExecutionPausedObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipeExecutionPausedObservation.
func (in *PipeExecutionPausedObservation) DeepCopy() *PipeExecutionPausedObservation {
	if in == nil {
		return nil
	}
	out := new(PipeExecutionPausedObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipeExecutionPausedParameters) DeepCopyInto(out *PipeExecutionPausedParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipeExecutionPausedParameters.
func (in *PipeExecutionPausedParameters) DeepCopy() *PipeExecutionPausedParameters {
	if in == nil {
		return nil
	}
	out := new(PipeExecutionPausedParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotedIdentifiersIgnoreCaseInitParameters) DeepCopyInto(out *QuotedIdentifiersIgnoreCaseInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotedIdentifiersIgnoreCaseInitParameters.
func (in *QuotedIdentifiersIgnoreCaseInitParameters) DeepCopy() *QuotedIdentifiersIgnoreCaseInitParameters {
	if in == nil {
		return nil
	}
	out := new(QuotedIdentifiersIgnoreCaseInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotedIdentifiersIgnoreCaseObservation) DeepCopyInto(out *QuotedIdentifiersIgnoreCaseObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotedIdentifiersIgnoreCaseObservation.
func (in *QuotedIdentifiersIgnoreCaseObservation) DeepCopy() *QuotedIdentifiersIgnoreCaseObservation {
	if in == nil {
		return nil
	}
	out := new(QuotedIdentifiersIgnoreCaseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotedIdentifiersIgnoreCaseParameters) DeepCopyInto(out *QuotedIdentifiersIgnoreCaseParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotedIdentifiersIgnoreCaseParameters.
func (in *QuotedIdentifiersIgnoreCaseParameters) DeepCopy() *QuotedIdentifiersIgnoreCaseParameters {
	if in == nil {
		return nil
	}
	out := new(QuotedIdentifiersIgnoreCaseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplaceInvalidCharactersInitParameters) DeepCopyInto(out *ReplaceInvalidCharactersInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplaceInvalidCharactersInitParameters.
func (in *ReplaceInvalidCharactersInitParameters) DeepCopy() *ReplaceInvalidCharactersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ReplaceInvalidCharactersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplaceInvalidCharactersObservation) DeepCopyInto(out *ReplaceInvalidCharactersObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplaceInvalidCharactersObservation.
func (in *ReplaceInvalidCharactersObservation) DeepCopy() *ReplaceInvalidCharactersObservation {
	if in == nil {
		return nil
	}
	out := new(ReplaceInvalidCharactersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplaceInvalidCharactersParameters) DeepCopyInto(out *ReplaceInvalidCharactersParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplaceInvalidCharactersParameters.
func (in *ReplaceInvalidCharactersParameters) DeepCopy() *ReplaceInvalidCharactersParameters {
	if in == nil {
		return nil
	}
	out := new(ReplaceInvalidCharactersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Schema) DeepCopyInto(out *Schema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Schema.
func (in *Schema) DeepCopy() *Schema {
	if in == nil {
		return nil
	}
	out := new(Schema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Schema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaInitParameters) DeepCopyInto(out *SchemaInitParameters) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.DataRetentionTimeInDays != nil {
		in, out := &in.DataRetentionTimeInDays, &out.DataRetentionTimeInDays
		*out = new(float64)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.DefaultDdlCollation != nil {
		in, out := &in.DefaultDdlCollation, &out.DefaultDdlCollation
		*out = new(string)
		**out = **in
	}
	if in.EnableConsoleOutput != nil {
		in, out := &in.EnableConsoleOutput, &out.EnableConsoleOutput
		*out = new(bool)
		**out = **in
	}
	if in.ExternalVolume != nil {
		in, out := &in.ExternalVolume, &out.ExternalVolume
		*out = new(string)
		**out = **in
	}
	if in.IsTransient != nil {
		in, out := &in.IsTransient, &out.IsTransient
		*out = new(string)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.MaxDataExtensionTimeInDays != nil {
		in, out := &in.MaxDataExtensionTimeInDays, &out.MaxDataExtensionTimeInDays
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PipeExecutionPaused != nil {
		in, out := &in.PipeExecutionPaused, &out.PipeExecutionPaused
		*out = new(bool)
		**out = **in
	}
	if in.QuotedIdentifiersIgnoreCase != nil {
		in, out := &in.QuotedIdentifiersIgnoreCase, &out.QuotedIdentifiersIgnoreCase
		*out = new(bool)
		**out = **in
	}
	if in.ReplaceInvalidCharacters != nil {
		in, out := &in.ReplaceInvalidCharacters, &out.ReplaceInvalidCharacters
		*out = new(bool)
		**out = **in
	}
	if in.StorageSerializationPolicy != nil {
		in, out := &in.StorageSerializationPolicy, &out.StorageSerializationPolicy
		*out = new(string)
		**out = **in
	}
	if in.SuspendTaskAfterNumFailures != nil {
		in, out := &in.SuspendTaskAfterNumFailures, &out.SuspendTaskAfterNumFailures
		*out = new(float64)
		**out = **in
	}
	if in.TaskAutoRetryAttempts != nil {
		in, out := &in.TaskAutoRetryAttempts, &out.TaskAutoRetryAttempts
		*out = new(float64)
		**out = **in
	}
	if in.TraceLevel != nil {
		in, out := &in.TraceLevel, &out.TraceLevel
		*out = new(string)
		**out = **in
	}
	if in.UserTaskManagedInitialWarehouseSize != nil {
		in, out := &in.UserTaskManagedInitialWarehouseSize, &out.UserTaskManagedInitialWarehouseSize
		*out = new(string)
		**out = **in
	}
	if in.UserTaskMinimumTriggerIntervalInSeconds != nil {
		in, out := &in.UserTaskMinimumTriggerIntervalInSeconds, &out.UserTaskMinimumTriggerIntervalInSeconds
		*out = new(float64)
		**out = **in
	}
	if in.UserTaskTimeoutMs != nil {
		in, out := &in.UserTaskTimeoutMs, &out.UserTaskTimeoutMs
		*out = new(float64)
		**out = **in
	}
	if in.WithManagedAccess != nil {
		in, out := &in.WithManagedAccess, &out.WithManagedAccess
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaInitParameters.
func (in *SchemaInitParameters) DeepCopy() *SchemaInitParameters {
	if in == nil {
		return nil
	}
	out := new(SchemaInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaList) DeepCopyInto(out *SchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Schema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaList.
func (in *SchemaList) DeepCopy() *SchemaList {
	if in == nil {
		return nil
	}
	out := new(SchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaObservation) DeepCopyInto(out *SchemaObservation) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.DataRetentionTimeInDays != nil {
		in, out := &in.DataRetentionTimeInDays, &out.DataRetentionTimeInDays
		*out = new(float64)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.DefaultDdlCollation != nil {
		in, out := &in.DefaultDdlCollation, &out.DefaultDdlCollation
		*out = new(string)
		**out = **in
	}
	if in.DescribeOutput != nil {
		in, out := &in.DescribeOutput, &out.DescribeOutput
		*out = make([]DescribeOutputObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnableConsoleOutput != nil {
		in, out := &in.EnableConsoleOutput, &out.EnableConsoleOutput
		*out = new(bool)
		**out = **in
	}
	if in.ExternalVolume != nil {
		in, out := &in.ExternalVolume, &out.ExternalVolume
		*out = new(string)
		**out = **in
	}
	if in.FullyQualifiedName != nil {
		in, out := &in.FullyQualifiedName, &out.FullyQualifiedName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsTransient != nil {
		in, out := &in.IsTransient, &out.IsTransient
		*out = new(string)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.MaxDataExtensionTimeInDays != nil {
		in, out := &in.MaxDataExtensionTimeInDays, &out.MaxDataExtensionTimeInDays
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]ParametersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PipeExecutionPaused != nil {
		in, out := &in.PipeExecutionPaused, &out.PipeExecutionPaused
		*out = new(bool)
		**out = **in
	}
	if in.QuotedIdentifiersIgnoreCase != nil {
		in, out := &in.QuotedIdentifiersIgnoreCase, &out.QuotedIdentifiersIgnoreCase
		*out = new(bool)
		**out = **in
	}
	if in.ReplaceInvalidCharacters != nil {
		in, out := &in.ReplaceInvalidCharacters, &out.ReplaceInvalidCharacters
		*out = new(bool)
		**out = **in
	}
	if in.ShowOutput != nil {
		in, out := &in.ShowOutput, &out.ShowOutput
		*out = make([]ShowOutputObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StorageSerializationPolicy != nil {
		in, out := &in.StorageSerializationPolicy, &out.StorageSerializationPolicy
		*out = new(string)
		**out = **in
	}
	if in.SuspendTaskAfterNumFailures != nil {
		in, out := &in.SuspendTaskAfterNumFailures, &out.SuspendTaskAfterNumFailures
		*out = new(float64)
		**out = **in
	}
	if in.TaskAutoRetryAttempts != nil {
		in, out := &in.TaskAutoRetryAttempts, &out.TaskAutoRetryAttempts
		*out = new(float64)
		**out = **in
	}
	if in.TraceLevel != nil {
		in, out := &in.TraceLevel, &out.TraceLevel
		*out = new(string)
		**out = **in
	}
	if in.UserTaskManagedInitialWarehouseSize != nil {
		in, out := &in.UserTaskManagedInitialWarehouseSize, &out.UserTaskManagedInitialWarehouseSize
		*out = new(string)
		**out = **in
	}
	if in.UserTaskMinimumTriggerIntervalInSeconds != nil {
		in, out := &in.UserTaskMinimumTriggerIntervalInSeconds, &out.UserTaskMinimumTriggerIntervalInSeconds
		*out = new(float64)
		**out = **in
	}
	if in.UserTaskTimeoutMs != nil {
		in, out := &in.UserTaskTimeoutMs, &out.UserTaskTimeoutMs
		*out = new(float64)
		**out = **in
	}
	if in.WithManagedAccess != nil {
		in, out := &in.WithManagedAccess, &out.WithManagedAccess
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaObservation.
func (in *SchemaObservation) DeepCopy() *SchemaObservation {
	if in == nil {
		return nil
	}
	out := new(SchemaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaParameters) DeepCopyInto(out *SchemaParameters) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.DataRetentionTimeInDays != nil {
		in, out := &in.DataRetentionTimeInDays, &out.DataRetentionTimeInDays
		*out = new(float64)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.DefaultDdlCollation != nil {
		in, out := &in.DefaultDdlCollation, &out.DefaultDdlCollation
		*out = new(string)
		**out = **in
	}
	if in.EnableConsoleOutput != nil {
		in, out := &in.EnableConsoleOutput, &out.EnableConsoleOutput
		*out = new(bool)
		**out = **in
	}
	if in.ExternalVolume != nil {
		in, out := &in.ExternalVolume, &out.ExternalVolume
		*out = new(string)
		**out = **in
	}
	if in.IsTransient != nil {
		in, out := &in.IsTransient, &out.IsTransient
		*out = new(string)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.MaxDataExtensionTimeInDays != nil {
		in, out := &in.MaxDataExtensionTimeInDays, &out.MaxDataExtensionTimeInDays
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PipeExecutionPaused != nil {
		in, out := &in.PipeExecutionPaused, &out.PipeExecutionPaused
		*out = new(bool)
		**out = **in
	}
	if in.QuotedIdentifiersIgnoreCase != nil {
		in, out := &in.QuotedIdentifiersIgnoreCase, &out.QuotedIdentifiersIgnoreCase
		*out = new(bool)
		**out = **in
	}
	if in.ReplaceInvalidCharacters != nil {
		in, out := &in.ReplaceInvalidCharacters, &out.ReplaceInvalidCharacters
		*out = new(bool)
		**out = **in
	}
	if in.StorageSerializationPolicy != nil {
		in, out := &in.StorageSerializationPolicy, &out.StorageSerializationPolicy
		*out = new(string)
		**out = **in
	}
	if in.SuspendTaskAfterNumFailures != nil {
		in, out := &in.SuspendTaskAfterNumFailures, &out.SuspendTaskAfterNumFailures
		*out = new(float64)
		**out = **in
	}
	if in.TaskAutoRetryAttempts != nil {
		in, out := &in.TaskAutoRetryAttempts, &out.TaskAutoRetryAttempts
		*out = new(float64)
		**out = **in
	}
	if in.TraceLevel != nil {
		in, out := &in.TraceLevel, &out.TraceLevel
		*out = new(string)
		**out = **in
	}
	if in.UserTaskManagedInitialWarehouseSize != nil {
		in, out := &in.UserTaskManagedInitialWarehouseSize, &out.UserTaskManagedInitialWarehouseSize
		*out = new(string)
		**out = **in
	}
	if in.UserTaskMinimumTriggerIntervalInSeconds != nil {
		in, out := &in.UserTaskMinimumTriggerIntervalInSeconds, &out.UserTaskMinimumTriggerIntervalInSeconds
		*out = new(float64)
		**out = **in
	}
	if in.UserTaskTimeoutMs != nil {
		in, out := &in.UserTaskTimeoutMs, &out.UserTaskTimeoutMs
		*out = new(float64)
		**out = **in
	}
	if in.WithManagedAccess != nil {
		in, out := &in.WithManagedAccess, &out.WithManagedAccess
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaParameters.
func (in *SchemaParameters) DeepCopy() *SchemaParameters {
	if in == nil {
		return nil
	}
	out := new(SchemaParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaSpec) DeepCopyInto(out *SchemaSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaSpec.
func (in *SchemaSpec) DeepCopy() *SchemaSpec {
	if in == nil {
		return nil
	}
	out := new(SchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaStatus) DeepCopyInto(out *SchemaStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaStatus.
func (in *SchemaStatus) DeepCopy() *SchemaStatus {
	if in == nil {
		return nil
	}
	out := new(SchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputInitParameters) DeepCopyInto(out *ShowOutputInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputInitParameters.
func (in *ShowOutputInitParameters) DeepCopy() *ShowOutputInitParameters {
	if in == nil {
		return nil
	}
	out := new(ShowOutputInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputObservation) DeepCopyInto(out *ShowOutputObservation) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.DroppedOn != nil {
		in, out := &in.DroppedOn, &out.DroppedOn
		*out = new(string)
		**out = **in
	}
	if in.IsCurrent != nil {
		in, out := &in.IsCurrent, &out.IsCurrent
		*out = new(bool)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(string)
		**out = **in
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.OwnerRoleType != nil {
		in, out := &in.OwnerRoleType, &out.OwnerRoleType
		*out = new(string)
		**out = **in
	}
	if in.RetentionTime != nil {
		in, out := &in.RetentionTime, &out.RetentionTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputObservation.
func (in *ShowOutputObservation) DeepCopy() *ShowOutputObservation {
	if in == nil {
		return nil
	}
	out := new(ShowOutputObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputParameters) DeepCopyInto(out *ShowOutputParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputParameters.
func (in *ShowOutputParameters) DeepCopy() *ShowOutputParameters {
	if in == nil {
		return nil
	}
	out := new(ShowOutputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSerializationPolicyInitParameters) DeepCopyInto(out *StorageSerializationPolicyInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSerializationPolicyInitParameters.
func (in *StorageSerializationPolicyInitParameters) DeepCopy() *StorageSerializationPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(StorageSerializationPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSerializationPolicyObservation) DeepCopyInto(out *StorageSerializationPolicyObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSerializationPolicyObservation.
func (in *StorageSerializationPolicyObservation) DeepCopy() *StorageSerializationPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(StorageSerializationPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSerializationPolicyParameters) DeepCopyInto(out *StorageSerializationPolicyParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSerializationPolicyParameters.
func (in *StorageSerializationPolicyParameters) DeepCopy() *StorageSerializationPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(StorageSerializationPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspendTaskAfterNumFailuresInitParameters) DeepCopyInto(out *SuspendTaskAfterNumFailuresInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspendTaskAfterNumFailuresInitParameters.
func (in *SuspendTaskAfterNumFailuresInitParameters) DeepCopy() *SuspendTaskAfterNumFailuresInitParameters {
	if in == nil {
		return nil
	}
	out := new(SuspendTaskAfterNumFailuresInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspendTaskAfterNumFailuresObservation) DeepCopyInto(out *SuspendTaskAfterNumFailuresObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspendTaskAfterNumFailuresObservation.
func (in *SuspendTaskAfterNumFailuresObservation) DeepCopy() *SuspendTaskAfterNumFailuresObservation {
	if in == nil {
		return nil
	}
	out := new(SuspendTaskAfterNumFailuresObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspendTaskAfterNumFailuresParameters) DeepCopyInto(out *SuspendTaskAfterNumFailuresParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspendTaskAfterNumFailuresParameters.
func (in *SuspendTaskAfterNumFailuresParameters) DeepCopy() *SuspendTaskAfterNumFailuresParameters {
	if in == nil {
		return nil
	}
	out := new(SuspendTaskAfterNumFailuresParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAutoRetryAttemptsInitParameters) DeepCopyInto(out *TaskAutoRetryAttemptsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAutoRetryAttemptsInitParameters.
func (in *TaskAutoRetryAttemptsInitParameters) DeepCopy() *TaskAutoRetryAttemptsInitParameters {
	if in == nil {
		return nil
	}
	out := new(TaskAutoRetryAttemptsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAutoRetryAttemptsObservation) DeepCopyInto(out *TaskAutoRetryAttemptsObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAutoRetryAttemptsObservation.
func (in *TaskAutoRetryAttemptsObservation) DeepCopy() *TaskAutoRetryAttemptsObservation {
	if in == nil {
		return nil
	}
	out := new(TaskAutoRetryAttemptsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAutoRetryAttemptsParameters) DeepCopyInto(out *TaskAutoRetryAttemptsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAutoRetryAttemptsParameters.
func (in *TaskAutoRetryAttemptsParameters) DeepCopy() *TaskAutoRetryAttemptsParameters {
	if in == nil {
		return nil
	}
	out := new(TaskAutoRetryAttemptsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceLevelInitParameters) DeepCopyInto(out *TraceLevelInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceLevelInitParameters.
func (in *TraceLevelInitParameters) DeepCopy() *TraceLevelInitParameters {
	if in == nil {
		return nil
	}
	out := new(TraceLevelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceLevelObservation) DeepCopyInto(out *TraceLevelObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceLevelObservation.
func (in *TraceLevelObservation) DeepCopy() *TraceLevelObservation {
	if in == nil {
		return nil
	}
	out := new(TraceLevelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceLevelParameters) DeepCopyInto(out *TraceLevelParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceLevelParameters.
func (in *TraceLevelParameters) DeepCopy() *TraceLevelParameters {
	if in == nil {
		return nil
	}
	out := new(TraceLevelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskManagedInitialWarehouseSizeInitParameters) DeepCopyInto(out *UserTaskManagedInitialWarehouseSizeInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskManagedInitialWarehouseSizeInitParameters.
func (in *UserTaskManagedInitialWarehouseSizeInitParameters) DeepCopy() *UserTaskManagedInitialWarehouseSizeInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserTaskManagedInitialWarehouseSizeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskManagedInitialWarehouseSizeObservation) DeepCopyInto(out *UserTaskManagedInitialWarehouseSizeObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskManagedInitialWarehouseSizeObservation.
func (in *UserTaskManagedInitialWarehouseSizeObservation) DeepCopy() *UserTaskManagedInitialWarehouseSizeObservation {
	if in == nil {
		return nil
	}
	out := new(UserTaskManagedInitialWarehouseSizeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskManagedInitialWarehouseSizeParameters) DeepCopyInto(out *UserTaskManagedInitialWarehouseSizeParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskManagedInitialWarehouseSizeParameters.
func (in *UserTaskManagedInitialWarehouseSizeParameters) DeepCopy() *UserTaskManagedInitialWarehouseSizeParameters {
	if in == nil {
		return nil
	}
	out := new(UserTaskManagedInitialWarehouseSizeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskMinimumTriggerIntervalInSecondsInitParameters) DeepCopyInto(out *UserTaskMinimumTriggerIntervalInSecondsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskMinimumTriggerIntervalInSecondsInitParameters.
func (in *UserTaskMinimumTriggerIntervalInSecondsInitParameters) DeepCopy() *UserTaskMinimumTriggerIntervalInSecondsInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserTaskMinimumTriggerIntervalInSecondsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskMinimumTriggerIntervalInSecondsObservation) DeepCopyInto(out *UserTaskMinimumTriggerIntervalInSecondsObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskMinimumTriggerIntervalInSecondsObservation.
func (in *UserTaskMinimumTriggerIntervalInSecondsObservation) DeepCopy() *UserTaskMinimumTriggerIntervalInSecondsObservation {
	if in == nil {
		return nil
	}
	out := new(UserTaskMinimumTriggerIntervalInSecondsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskMinimumTriggerIntervalInSecondsParameters) DeepCopyInto(out *UserTaskMinimumTriggerIntervalInSecondsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskMinimumTriggerIntervalInSecondsParameters.
func (in *UserTaskMinimumTriggerIntervalInSecondsParameters) DeepCopy() *UserTaskMinimumTriggerIntervalInSecondsParameters {
	if in == nil {
		return nil
	}
	out := new(UserTaskMinimumTriggerIntervalInSecondsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskTimeoutMsInitParameters) DeepCopyInto(out *UserTaskTimeoutMsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskTimeoutMsInitParameters.
func (in *UserTaskTimeoutMsInitParameters) DeepCopy() *UserTaskTimeoutMsInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserTaskTimeoutMsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskTimeoutMsObservation) DeepCopyInto(out *UserTaskTimeoutMsObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskTimeoutMsObservation.
func (in *UserTaskTimeoutMsObservation) DeepCopy() *UserTaskTimeoutMsObservation {
	if in == nil {
		return nil
	}
	out := new(UserTaskTimeoutMsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTaskTimeoutMsParameters) DeepCopyInto(out *UserTaskTimeoutMsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTaskTimeoutMsParameters.
func (in *UserTaskTimeoutMsParameters) DeepCopy() *UserTaskTimeoutMsParameters {
	if in == nil {
		return nil
	}
	out := new(UserTaskTimeoutMsParameters)
	in.DeepCopyInto(out)
	return out
}
