// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"

// GetCondition of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetPublishConnectionDetailsTo of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return mg.Spec.PublishConnectionDetailsTo
}

// GetWriteConnectionSecretToReference of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetPublishConnectionDetailsTo of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) SetPublishConnectionDetailsTo(r *xpv1.PublishConnectionDetailsTo) {
	mg.Spec.PublishConnectionDetailsTo = r
}

// SetWriteConnectionSecretToReference of this AuthenticationIntegrationWithClientCredentials.
func (mg *AuthenticationIntegrationWithClientCredentials) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
